dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('df_user.urls')),
    url(r'^',include('df_goods.urls')),
    url(r'^cart/', include('df_cart.urls')),
    url(r'^order/', include('df_order.urls')),
    url(r'^search/', include('haystack.urls')),
]

dailyfresh/df_cart/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^add(\d+)_(\d+)/$', views.add),
    url(r'^$', views.list),
    url(r'^count_change/$', views.count_change),
    url(r'^order/$', views.order),
]

dailyfresh/df_user/urls.py
from django.conf.urls import url
import views


urlpatterns = [
    url(r'^login/$', views.login),
    url(r'^login_handle/$', views.login_handle),
    url(r'^register/$', views.register),
    url(r'^register_exist/$', views.register_exist),
    url(r'^register_handle/$', views.register_handle),
    url(r'^info/$', views.info),
    url(r'^order(\d*)/$', views.order),
    url(r'^site/$', views.site),
    url(r'logout/$', views.logout),
]

dailyfresh/df_order/models.py
from django.db import models

# Create your models here.
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('df_user.User_info')
    odate = models.DateTimeField(auto_now_add=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6,decimal_places=2)
    oaddress = models.CharField(max_length=150)
    class Meta:
        db_table='OrderInfo'

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=5,decimal_places=2)
    count = models.IntegerField()
    class Meta:
        db_table='OrderDetailInfo'

dailyfresh/df_user/models.py
# coding=utf-8
from django.db import models

# Create your models here.
# 定义user模型类
class User_info(models.Model):
    #用户信息
    user_name = models.CharField(max_length=20)
    user_passwd = models.CharField(max_length=40)
    user_mail = models.CharField(max_length=30)
    #用户中心
    consignee_name = models.CharField(max_length=20, default='')
    consignee_address = models.CharField(max_length=20, default='')
    consignee_postcode = models.CharField(max_length=20, default='')
    consignee_tel = models.CharField(max_length=20, default='')

    class Meta:
        db_table = 'user_info'

dailyfresh/df_user/views.py
# coding=utf-8
from django.shortcuts import render,redirect
from django.http import JsonResponse,HttpResponseRedirect
from hashlib import sha1
from models import *
from df_goods.models import *
from df_order.models import *
from django.core.paginator import Paginator,Page
import user_decorator

# Create your views here.

def login(request):
    uname = request.COOKIES.get('uname','')
    context = {'title':'用户登录','error_name': 0,'error_pwd': 0,'uname':uname}
    return render(request, 'df_user/login.html', context)

def login_handle(request):
    #　接收请求信息
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    jizhu = post.get('jizhu', 0)
    print jizhu
    #　根据用户名查询对象
    users = User_info.objects.filter(user_name=uname)
    print users
    #　判断１.未查到则用户名错　２.查询到　则判断密码是否正确, 正确则转到用户中心
    if len(users)==1:
        s1 = sha1()
        s1.update(upwd)
        print s1.hexdigest()
        print users[0].user_passwd
        # 　查询集第一条数据upwd属性
        if s1.hexdigest()==users[0].user_passwd:

            #读取cookies中设置的url为根目录
            #这句话怎么理解?读取cookies,没有读取到则设置一个默认值？
            url = request.COOKIES.get('url','/user/site/')

            red = HttpResponseRedirect(url)
            # 成功后删除转向地址，防止以后直接登录造成的转向
            # 为什么要删除?
            red.set_cookie('url','',max_age=-1)

            #记住用户名
            if jizhu!=0:
                print uname
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname','',max_age=-1)
            # 记住用户名为什么不直接存session,反而要先存cookies?
            request.session['user_id']=users[0].id
            request.session['user_name']=uname
            return red
        else:
            context = {'title':'用户登陆','error_name':0,'error_pwd':1,'uname':uname,'upwd':upwd}
            return render(request, 'df_user/login.html', context)
    else:
        context = {'title': '用户登录','error_name':1,'error_pwd': 0,'uname':uname,'upwd':upwd}
        return render(request,'df_user/login.html',context)


def register(request):
    context = {'title':'天天生鲜-注册'}
    return render(request, 'df_user/register.html', context)

def register_exist(request):
    user = request.GET.get('user_name')
    count = User_info.objects.filter(user_name=user).count()
    return JsonResponse({'count':count})

def register_handle(request):
    #{'user':user_name,'pwd':pwd,'cpwd':cpwd,'email':email,'allow':allow};
    #接收用户输入
    dict = request.POST
    user_name = dict.get('user_name')
    pwd = dict.get('pwd')
    cpwd = dict.get('cpwd')
    email = dict.get('email')

    #密码加密
    s1=sha1()
    s1.update(pwd)
    pwd2 = s1.hexdigest()

    #创建对象
    user = User_info()
    user.user_name = user_name
    user.user_passwd = pwd2
    user.user_mail = email
    user.save()
    #注册成功,返回登陆页面
    #ajax使用的是局部刷新,这里重定向的返回值并没有传递给浏览器,而是传递给ajax的function方法
    #return redirect('/user/login/')
    return JsonResponse({'redirect':'/user/login/'})

def logout(request):
    request.session.flush()
    return redirect('/')

@user_decorator.login
def info(request):
    user = User_info.objects.get(id=request.session['user_id'])
    history_list = []
    history = request.COOKIES.get('history','')
    if history != '':
        # 将字符串拆分成列表
        history1 = history.split(',')
        for goods_id in history1:
            history_list.append(GoodsInfo.objects.get(id=int(goods_id)))

    context = {'title': '用户中心',
               'user': user,
               'history_list':history_list,
               }
    return render(request, 'df_user/user_center_info.html', context)

@user_decorator.login
def order(request,pindex):
    order_list=OrderInfo.objects.filter(user_id=request.session['user_id']).order_by('-oid')
    paginator = Paginator(order_list,2)
    if pindex == '':
        pindex = '1'
    page = paginator.page(int(pindex))

    context = {'title': '用户中心',
               'page_name':1,
               'paginator':paginator,
               'page':page,
               }
    return render(request, 'df_user/user_center_order.html',context)

@user_decorator.login
def site(request):
    #从session中保存的信息获取当前用户对象
    user = User_info.objects.get(id=request.session['user_id'])


    #如果有数据提交,获取post表单数据,这里应该在写一段js代码进行判断
    #if request.method=='POST':
    dict = request.POST
    user.consignee_name = dict.get('uname')
    user.consignee_address = dict.get('uaddress')
    user.consignee_postcode = dict.get('upostcode')
    user.consignee_tel = dict.get('utel')
    user.save()
    #从数据库读取地址信息
    context = {'title':'用户中心',
               'user':user,
               }
    return render(request, 'df_user/user_center_site.html', context)

dailyfresh/templates/df_user/login.html
{% extends "base_foot.html"%}
    {%block head%}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		//添加js代码进行用户登陆验证
		$(function () {
			name_error = false;
			name_error = false;
			// 若用户名密码错误,提交数据后,页面刷新后仍能够显示错误信息
			if({{error_name}}==1){
			    $('.user_error').html('用户名错误').show();
			}
			if({{error_pwd}}==1){
			    $('.pwd_error').html('密码错误').show();
			}

			//判断用户名为空
			$('.name_input').blur(function () {
				if($('.name_input').val().length==0){
				    $('.user_error').html('请输入用户名').show();
				    name_error = false;
				}else{
				    $('.user_error').hide();
				    name_error = true;
				}
            })
			//判断密码为空
			$('.pass_input').blur(function () {
				if($('.pass_input').val().length==0){
				    $('.pwd_error').html('请输入用密码').show();
				    pwd_error = false;
				}else{
				    $('.user_error').hide();
				    pwd_error = true;
				}
            });

			//提交form表单
			$('.form_input').submit(function () {
			    //失去焦点,在提交之前进行一次判断
				$('.name_input').blur();
				$('.pass_input').blur();
				//当用户名和密码输入后才能进行提交操作
				return name_error && pwd_error
            });






        });

	</script>
    {%endblock head%}

    {%block body%}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" id="reg_form" action="/user/login_handle/">
						{%csrf_token%}
						<input type="text" name="username" id="username" class="name_input" placeholder="请输入用户名" value="{{uname}}">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" id="pwd" class="pass_input" placeholder="请输入密码" value="{{upwd}}">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    {%endblock body%}



dailyfresh/templates/df_user/register.html
{% extends "base_foot.html"%}
    {%block head%}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
	<script type="text/javascript">
	    // 添加以下代码使在js中的ajax能够通过csrf验证
		$.ajaxSetup({
    		data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
		});
	</script>
    {%endblock head%}

    {%block body%}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<!--form默认提交方式为get,改成post后，需要开启csrf_token-->
				<form method="post" id="reg_form" action="/user/register_handle/">
					{%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
    {%endblock body%}


dailyfresh/templates/df_user/user_center_info.html
{% extends 'base.html'%}
{%block content%}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order">· 全部订单</a></li>
				<li><a href="/user/site">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user.user_name}}</li>
							<li><span>联系方式：</span>{{user.consignee_tel}}</li>
							<li><span>联系地址：</span>{{user.consignee_address}}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				{% for goods in history_list %}
				<li>
					<a href="/{{goods.id}}/"><img src="/static/{{goods.gpic}}"></a>
					<h4><a href="/{{goods.id}}/">{{goods.gtitle}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{goods.gprice}}</span>
						<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
						<a href="#" class="add_goods" title="加入购物车"><a>
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>
		</div>
	</div>
{%endblock content%}




dailyfresh/templates/df_user/user_center_order.html
{% extends 'base.html'%}
{%block head%}
<script>
	$(function () {
		$('.col04').each(function () {
			num=parseFloat($(this).prev().text())
			price=parseFloat($(this).prev().prev().find('span').text())
			$(this).text(num*price+'元')
        });
    });
</script>
{%endblock head%}
{%block content%}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{% if paginator.count > 0%}
				{% for order in page%}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.odate}}</li>
					<li class="col02">订单号：{{order.oid}}</li>
					<li class="col02 stress">
						{% if order.oIsPay%}已支付{%else%}未支付{%endif%}
					</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for detail in order.orderdetailinfo_set.all%}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{detail.goods.gpic}}"></li>
									<li class="col02">{{detail.goods.gtitle|slice:'10'}}<em><span>{{detail.price}}</span>元/{{detail.goods.gunit}}</em></li>
									<li class="col03">{{detail.count}}</li>
									<li class="col04">0元</li>
								</ul>
								{% endfor %}

							</td>
							<td width="15%">{{order.ototal}}元</td>
							{% if order.oIsPay %}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
							{%else%}
							<td width="15%">待付款</td>
						<td width="15%"><a href="/order/pay{{order.oid}}/" class="oper_btn">去付款</a></td>
							{%endif%}
						</tr>
					</tbody>
				</table>
				{% endfor %}

				<div class="pagenation">
					{% if page.has_previous%}
					<a href="/user/order{{page.previous_page_number}}/">上一页</a>
					{% endif %}

					{% for pindex in paginator.page_range%}
					{% if pindex == page.number%}
					<a href="#" class="active">{{pindex}}</a>
					{%else%}
					<a href="/user/order{{pindex}}/">{{pindex}}</a>
					{%endif%}
					{%endfor%}

					{%if page.has_next%}
					<a href="/user/order{{page.next_page_number}}/">下一页></a>
					{%endif%}
					</div>
				{%else%}
				暂无订单信息
			{% endif %}
		</div>
	</div>
{%endblock content%}

dailyfresh/templates/df_user/user_center_site.html
{% extends 'base.html'%}
{% block content%}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<!--北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528-->
						<dd>{{user.consignee_address}} （{{user.consignee_name}} 收） {{user.consignee_tel}}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<!--采用post方式提交表单-->
					<form method="post" action="/user/site/">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="uname" value=" ">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="upostcode">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="utel">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{%endblock content%}
